### PR TITLE
Feat/update workspace members

### PR DESCRIPTION
**Pull request by RobWalt**
Picking up #105 

I'll describe it better soon

---

## Regarding the formatting

- It keeps the same whitespace style
  ```
  [workspace]
  members = [
        "a",
  ]
  ```
  to
  ```
  [workspace]
  members = [
        "a",
        "b",
  ]
  ```
- it defaults to newline style
  ```
  [workspace]
  ```
  or 
  ```
  [workspace]
  members = []
  ```
  to 
  ```
  [workspace]
  members = [
    "a",
  ]
  ```
  and
- it actually also keeps the inline formatting if it's there
  ```
  [workspace]
  members = [ "a", "b", "c", ]
  ```
  to
  ```
  [workspace]
  members = [ "a", "b", "c", "d", ]
  ```

---

Bugs:

- if `./b` exists and we create `cargo ws create abc/b` then it fails and deletes `./b` because of the cleanup

### CODE REVIEW

**Comment by pksunkara** [comment]
Thanks for the contribution. What's with hw niz configs?

**Comment by RobWalt** [comment]
It's for providing a reproducible development environment if you you the nix package manager or are running NixOS. But it's not limited to that, you can also provide a way of building and installing it even if you don't have rust installed at all (although that makes no real sense with `cargo-workspaces`)

I can remove that though

**Comment by RobWalt** [comment]
Btw you can merge it if you want. Otherwise I would try to get the glob matching issue right before merging it.

**Comment by RobWalt** [comment]
The glob checking should work now. In

```
[workspace]
members = [
  "a",
  "abc/*,
]
```

it checks every `Cargo.toml` file matching under the `abc/*` glob if it already contains the package name. This is done both for the `workspace.exclude` list to detect the creation of unwanted things and the `workspace.members` list to detect duplicates

**Pull request merged**
